### ISSUE TITLE
Issue with exploded war on tomcat

### ISSUE THREAD

**Issue by lstocchi** [robstryker/rsp-server-extras#11]
when i add an exploded deployment to tomcat it works great but there is an issue when opening it in the browser. If i use `demo.war` as the deployment.output.name then the url to see my app will be `localhost/demo.war` but the "open in browser" action opens `localhost/demo` which results in a 404

**Comment by robstryker** [comment]
According to this link:  https://octopus.com/blog/defining-tomcat-context-paths

You are supposed to deploy exploded folders in tomcat as their name with no suffix. So you're supposed to use the output name of "demo" and not "demo.war".

**Comment by robstryker** [comment]
Seems there's a bug doing that too. Seems tomcat only has 'war' in our approved suffix list, but if we're supposed to allow exploded directories with any name, we need to disable that.  I've added a blank suffix as an approved suffix which all deployments should match I guess.
